<a href="https://colab.research.google.com/github/ydv-prince/Machine-Learning/blob/main/2_Lasso%2C_RIdge%2C_ElasticNet_%26_hyperparameter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.filterwarnings('ignore')

In [11]:
df = sns.load_dataset('mpg')

In [12]:
df

      mpg  cylinders  ...  origin                       name
0    18.0          8  ...     usa  chevrolet chevelle malibu
1    15.0          8  ...     usa          buick skylark 320
2    18.0          8  ...     usa         plymouth satellite
3    16.0          8  ...     usa              amc rebel sst
4    17.0          8  ...     usa                ford torino
..    ...        ...  ...     ...                        ...
393  27.0          4  ...     usa            ford mustang gl
394  44.0          4  ...  europe                  vw pickup
395  32.0          4  ...     usa              dodge rampage
396  28.0          4  ...     usa                ford ranger
397  31.0          4  ...     usa                 chevy s-10

[398 rows x 9 columns]

In [13]:
df.drop("name", axis=1, inplace = True)

In [14]:
df.head()

    mpg  cylinders  displacement  ...  acceleration  model_year  origin
0  18.0          8         307.0  ...          12.0          70     usa
1  15.0          8         350.0  ...          11.5          70     usa
2  18.0          8         318.0  ...          11.0          70     usa
3  16.0          8         304.0  ...          12.0          70     usa
4  17.0          8         302.0  ...          10.5          70     usa

[5 rows x 8 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [16]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
dtype: object

In [17]:
df.shape

(398, 8)

In [18]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [20]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

In [21]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [23]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [24]:
#data encoding
df["origin"] = df["origin"].map({"usa":1, "japan":2, "europe":3})

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [26]:
X = df.drop('mpg', axis= 1)
y = df['mpg']

In [27]:
X

     cylinders  displacement  horsepower  ...  acceleration  model_year  origin
0            8         307.0       130.0  ...          12.0          70       1
1            8         350.0       165.0  ...          11.5          70       1
2            8         318.0       150.0  ...          11.0          70       1
3            8         304.0       150.0  ...          12.0          70       1
4            8         302.0       140.0  ...          10.5          70       1
..         ...           ...         ...  ...           ...         ...     ...
393          4         140.0        86.0  ...          15.6          82       1
394          4          97.0        52.0  ...          24.6          82       3
395          4         135.0        84.0  ...          11.6          82       1
396          4         120.0        79.0  ...          18.6          82       1
397          4         119.0        82.0  ...          19.4          82       1

[398 rows x 7 columns]

In [28]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [29]:
#train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=1)

In [3]:
# CV with hyperparameter tuning

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import Lasso, Ridge

In [30]:
X_train.shape

(278, 7)

In [31]:
X_test.shape

(120, 7)

In [32]:
# gridsearchCV for lasso
# define by model

lasso = Lasso()

In [33]:
lasso

Lasso()

In [34]:
#grid search cv>> Dictionary with parameters names (str) as keys and lists of parameter settings to try as value

param_grid = {'alpha': [0.001, 0.01, 0.1, 1,2,5,10,100]}
param_grid

{'alpha': [0.001, 0.01, 0.1, 1, 2, 5, 10, 100]}

In [35]:
grid_search = GridSearchCV(estimator= lasso, param_grid= param_grid, cv= 5, scoring= 'r2', verbose= 2)

In [36]:
grid_search

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 2, 5, 10, 100]},
             scoring='r2', verbose=2)

In [37]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 2, 5, 10, 100]},
             scoring='r2', verbose=2)

In [38]:
grid_search.best_params_

{'alpha': 0.1}

In [41]:
grid_search.best_params_['alpha']

0.1

In [42]:
grid_search.best_score_
#Mean cross-validated score of the best_estimator

np.float64(0.7964209726696481)

In [43]:
grid_search.best_estimator_
#Estimator that was chosen by the search, i.e. estimator which gave highest score (or smallest loss if specified) on the left out data

Lasso(alpha=0.1)

In [45]:
from sklearn.metrics import r2_score

In [46]:
y_pred = grid_search.best_estimator_.predict(X_test)
r2_grid = r2_score(y_test, y_pred)
print(f"The R square of GridSearchCV of Lasso regression: {r2_grid}")

The R square of GridSearchCV of Lasso regression: 0.8345318641232303