<a href="https://colab.research.google.com/github/ydv-prince/Machine-Learning/blob/main/Linear_models_tips_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [57]:
df = sns.load_dataset('tips')

In [58]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [59]:
X

     total_bill  sex  smoker  day  time  size
0         16.99  2.0     0.0  4.0   1.0     2
1         10.34  1.0     0.0  4.0   1.0     3
2         21.01  1.0     0.0  4.0   1.0     3
3         23.68  1.0     0.0  4.0   1.0     2
4         24.59  2.0     0.0  4.0   1.0     4
..          ...  ...     ...  ...   ...   ...
239       29.03  1.0     0.0  3.0   1.0     3
240       27.18  2.0     1.0  3.0   1.0     2
241       22.67  1.0     1.0  3.0   1.0     2
242       17.82  1.0     0.0  3.0   1.0     2
243       18.78  2.0     0.0  1.0   1.0     2

[244 rows x 6 columns]

In [60]:
df.sex.unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [61]:
df['sex'] = df['sex'].map({'Male':1, 'Female':2})

In [62]:
df['smoker'] = df['smoker'].map({'No':0, 'Yes':1})
df['day'] = df['day'].map({'Thur':1, 'Fri':2, 'Sat':3, 'Sun':4})
df['time'] = df['time'].map({'Dinner':1, 'Lunch': 2})

In [63]:
df['sex'] = df['sex'].astype(float)
df['smoker'] = df['smoker'].astype(float)
df['day'] = df['day'].astype(float)
df['time'] = df['time'].astype(float)

In [64]:
df

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01  2.0     0.0  4.0   1.0     2
1         10.34  1.66  1.0     0.0  4.0   1.0     3
2         21.01  3.50  1.0     0.0  4.0   1.0     3
3         23.68  3.31  1.0     0.0  4.0   1.0     2
4         24.59  3.61  2.0     0.0  4.0   1.0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92  1.0     0.0  3.0   1.0     3
240       27.18  2.00  2.0     1.0  3.0   1.0     2
241       22.67  2.00  1.0     1.0  3.0   1.0     2
242       17.82  1.75  1.0     0.0  3.0   1.0     2
243       18.78  3.00  2.0     0.0  1.0   1.0     2

[244 rows x 7 columns]

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    float64
 3   smoker      244 non-null    float64
 4   day         244 non-null    float64
 5   time        244 non-null    float64
 6   size        244 non-null    int64
dtypes: float64(6), int64(1)
memory usage: 13.5 KB

In [66]:
X = df.drop('tip', axis=1)
y = df['tip']

In [67]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state= 1, train_size= 0.8)

In [69]:
X_train.shape

(195, 6)

In [70]:
X_test.shape

(49, 6)

In [71]:
y_train.shape

(195,)

In [72]:
y_test.shape

(49,)

In [73]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [74]:
model

LinearRegression()

In [75]:
model.fit(X_train,y_train)

LinearRegression()

In [76]:
y_pred = model.predict(X_test)

In [77]:
from sklearn.metrics import r2_score
score = r2_score(y_test, y_pred)
print(f"R2 Score of Linear model: {score}")

R2 Score of Linear model: 0.49755299573499767