In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
# predict the total_bill? i.e. total_bill is target variable
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [4]:
#EDA>> subjective
#encoding, missing value treatment, scaling>> automate
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [5]:
X = df.drop('total_bill', axis =1)
y = df['total_bill']

In [6]:
X.shape, y.shape

((244, 6), (244,))

In [7]:
X

      tip     sex smoker   day    time  size
0    1.01  Female     No   Sun  Dinner     2
1    1.66    Male     No   Sun  Dinner     3
2    3.50    Male     No   Sun  Dinner     3
3    3.31    Male     No   Sun  Dinner     2
4    3.61  Female     No   Sun  Dinner     4
..    ...     ...    ...   ...     ...   ...
239  5.92    Male     No   Sat  Dinner     3
240  2.00  Female    Yes   Sat  Dinner     2
241  2.00    Male    Yes   Sat  Dinner     2
242  1.75    Male     No   Sat  Dinner     2
243  3.00  Female     No  Thur  Dinner     2

[244 rows x 6 columns]

In [8]:
y

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.3)

In [10]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((170, 6), (74, 6), (170,), (74,))

In [11]:
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [12]:
#Handling the missing value
#data encoding
#feature scaling

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [14]:
cat_cols = ["sex", "smoker", "day", "time"]
num_cols = ["tip", "size"]

In [15]:
#feature engineering automation using pipeline and columntransformer

num_pipeline = Pipeline(steps= [('imputation', SimpleImputer(strategy= 'median')),
                                ('scaling', StandardScaler())])

cat_pipeline = Pipeline(steps= [('imputation', SimpleImputer(strategy= 'most_frequent')),
                                ('encoding', OneHotEncoder())])

preprocessor = ColumnTransformer([("num_pipeline", num_pipeline, num_cols),
                                  ("cat_pipeline", cat_pipeline, cat_cols)])

preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['tip', 'size']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder())]),
                                 ['sex', 'smoker', 'day', 'time'])])

In [16]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [17]:
X_train

array([[ 0.32430182, -0.61738008,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.5043048 ,  1.38175543,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.74190872, -0.61738008,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.75571601, -0.61738008,  0.        , ...,  1.        ,
         0.        ,  1.        ],
       [-0.39571006, -0.61738008,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 1.20991645,  1.38175543,  0.        , ...,  0.        ,
         1.        ,  0.        ]])

In [18]:
X_test

array([[-0.75571601, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ],
       [-0.75571601, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.53251232,  0.38218767,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.53971244, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-1.11572195, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.41731042, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.03570412,  0.38218767,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.22290721,  0.38218767,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.69091494, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.68430777, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.83632679,  1.38175543,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.87232738, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.03570412, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         1.        ,  0.        ],
       [-0.21570709, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.68430777, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.30990159, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.21570709, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.11572195, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.03570412,  1.38175543,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.03570412,  1.38175543,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.62611387,  0.38218767,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.30990159, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ],
       [-0.39571006, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.24510052, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.75571601, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.03570412, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.15869909, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.09389802, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.46852777, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.73411565, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.03570412, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.07252124, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.74851589, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.09330507,  1.38175543,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-1.29572492, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.40350313,  1.38175543,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-1.01492028, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.75571601, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 2.48433748,  0.38218767,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.30990159,  0.38218767,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 2.06673059,  0.38218767,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.39571006, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ],
       [-0.77011624, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.68430777,  0.38218767,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.40431965,  0.38218767,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.03652064, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.68430777,  0.38218767,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.96451945, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.75571601,  1.38175543,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.39630301,  0.38218767,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.32430182,  0.38218767,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.03570412, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.82831015,  3.38089093,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.35970947, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.89971838, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.75571601, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.03570412,  0.38218767,  1.        ,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ],
       [-1.11572195, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.74190872, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 4.2843672 ,  1.38175543,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.75571601,  0.38218767,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.61171363, -0.61738008,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.72750848, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.47572789, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.75571601, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.87811803, -1.61694784,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.75571601, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-1.35332587, -0.61738008,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.05069731,  1.38175543,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.75571601, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.78451648, -0.61738008,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.90031133, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.25950075,  0.38218767,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.75571601, -0.61738008,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ]])

In [19]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [20]:
models = {
    "support_vector_regressor": SVR(),
    "DT Regressor": DecisionTreeRegressor(),
    "Multiple Linear Regression": LinearRegression(),
    "random_forest": RandomForestRegressor()
}

models

{'support_vector_regressor': SVR(),
 'DT Regressor': DecisionTreeRegressor(),
 'Multiple Linear Regression': LinearRegression(),
 'random_forest': RandomForestRegressor()}

In [21]:
from sklearn.metrics import r2_score

In [22]:
def model_train_evaluation(X_train, y_train, X_test, y_test, models):
  evaluation = {}
  for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    model_score = r2_score(y_test, y_pred)
    evaluation[list(models.keys())[i]] = model_score
  return evaluation

In [23]:
model_train_evaluation(X_train, y_train, X_test, y_test, models)

{'support_vector_regressor': 0.4030934570045954,
 'DT Regressor': 0.2516266464223609,
 'Multiple Linear Regression': 0.535899462117648,
 'random_forest': 0.48779883587613226}

In [24]:
from sklearn.ensemble import RandomForestRegressor

In [25]:
rf_r = RandomForestRegressor(oob_score= True)
rf_r

RandomForestRegressor(oob_score=True)

In [26]:
from sklearn.model_selection import RandomizedSearchCV
params={'max_depth':[1,50, 100, 150,200],
        'n_estimators':[50, 100,200]}

In [27]:
reg = RandomizedSearchCV(rf_r, param_distributions= params, cv= 5, verbose= 3, scoring= 'r2')
reg

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(oob_score=True),
                   param_distributions={'max_depth': [1, 50, 100, 150, 200],
                                        'n_estimators': [50, 100, 200]},
                   scoring='r2', verbose=3)

In [28]:
reg.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END .....max_depth=50, n_estimators=50;, score=0.492 total time=   0.2s
[CV 2/5] END .....max_depth=50, n_estimators=50;, score=0.387 total time=   0.2s
[CV 3/5] END .....max_depth=50, n_estimators=50;, score=0.584 total time=   0.4s
[CV 4/5] END .....max_depth=50, n_estimators=50;, score=0.463 total time=   0.2s
[CV 5/5] END .....max_depth=50, n_estimators=50;, score=0.563 total time=   0.2s
[CV 1/5] END ...max_depth=150, n_estimators=100;, score=0.523 total time=   0.5s
[CV 2/5] END ...max_depth=150, n_estimators=100;, score=0.349 total time=   0.3s
[CV 3/5] END ...max_depth=150, n_estimators=100;, score=0.593 total time=   0.9s
[CV 4/5] END ...max_depth=150, n_estimators=100;, score=0.432 total time=   0.6s
[CV 5/5] END ...max_depth=150, n_estimators=100;, score=0.542 total time=   0.3s
[CV 1/5] END ...max_depth=200, n_estimators=200;, score=0.521 total time=   1.3s
[CV 2/5] END ...max_depth=200, n_estimators=200;, score=0.363 total time=   1.4s
[CV 3/5] END ...max_depth=200, n_estimators=200;, score=0.592 total time=   0.8s
[CV 4/5] END ...max_depth=200, n_estimators=200;, score=0.439 total time=   0.6s
[CV 5/5] END ...max_depth=200, n_estimators=200;, score=0.549 total time=   0.7s
[CV 1/5] END ...max_depth=150, n_estimators=200;, score=0.513 total time=   0.5s
[CV 2/5] END ...max_depth=150, n_estimators=200;, score=0.357 total time=   0.5s
[CV 3/5] END ...max_depth=150, n_estimators=200;, score=0.589 total time=   0.3s
[CV 4/5] END ...max_depth=150, n_estimators=200;, score=0.426 total time=   0.3s
[CV 5/5] END ...max_depth=150, n_estimators=200;, score=0.537 total time=   0.3s
[CV 1/5] END ...max_depth=100, n_estimators=100;, score=0.485 total time=   0.1s
[CV 2/5] END ...max_depth=100, n_estimators=100;, score=0.313 total time=   0.1s
[CV 3/5] END ...max_depth=100, n_estimators=100;, score=0.576 total time=   0.2s
[CV 4/5] END ...max_depth=100, n_estimators=100;, score=0.437 total time=   0.1s
[CV 5/5] END ...max_depth=100, n_estimators=100;, score=0.567 total time=   0.1s
[CV 1/5] END ....max_depth=50, n_estimators=100;, score=0.528 total time=   0.1s
[CV 2/5] END ....max_depth=50, n_estimators=100;, score=0.297 total time=   0.1s
[CV 3/5] END ....max_depth=50, n_estimators=100;, score=0.577 total time=   0.1s
[CV 4/5] END ....max_depth=50, n_estimators=100;, score=0.426 total time=   0.2s
[CV 5/5] END ....max_depth=50, n_estimators=100;, score=0.532 total time=   0.2s
[CV 1/5] END ...max_depth=100, n_estimators=200;, score=0.509 total time=   0.4s
[CV 2/5] END ...max_depth=100, n_estimators=200;, score=0.326 total time=   0.3s
[CV 3/5] END ...max_depth=100, n_estimators=200;, score=0.586 total time=   0.3s
[CV 4/5] END ...max_depth=100, n_estimators=200;, score=0.404 total time=   0.3s
[CV 5/5] END ...max_depth=100, n_estimators=200;, score=0.555 total time=   0.3s
[CV 1/5] END .....max_depth=1, n_estimators=200;, score=0.356 total time=   0.2s
[CV 2/5] END .....max_depth=1, n_estimators=200;, score=0.223 total time=   0.2s
[CV 3/5] END .....max_depth=1, n_estimators=200;, score=0.444 total time=   0.2s
[CV 4/5] END .....max_depth=1, n_estimators=200;, score=0.290 total time=   0.3s
[CV 5/5] END .....max_depth=1, n_estimators=200;, score=0.349 total time=   0.2s
[CV 1/5] END .....max_depth=1, n_estimators=100;, score=0.356 total time=   0.1s
[CV 2/5] END .....max_depth=1, n_estimators=100;, score=0.193 total time=   0.1s
[CV 3/5] END .....max_depth=1, n_estimators=100;, score=0.447 total time=   0.1s
[CV 4/5] END .....max_depth=1, n_estimators=100;, score=0.292 total time=   0.1s
[CV 5/5] END .....max_depth=1, n_estimators=100;, score=0.346 total time=   0.1s
[CV 1/5] END ....max_depth=200, n_estimators=50;, score=0.440 total time=   0.1s
[CV 2/5] END ....max_depth=200, n_estimators=50;, score=0.353 total time=   0.1s
[CV 3/5] END ....max_depth=200, n_estimators=50;, score=0.578 total time=   0.1s
[CV 4/5] END ....max_depth=200, n_estimators=50;, score=0.396 total time=   0.1s
[CV 5/5] END ....max_depth=200, n_estimators=50;, score=0.542 total time=   0.1s

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(oob_score=True),
                   param_distributions={'max_depth': [1, 50, 100, 150, 200],
                                        'n_estimators': [50, 100, 200]},
                   scoring='r2', verbose=3)

In [29]:
reg.best_params_

{'n_estimators': 50, 'max_depth': 50}

In [30]:
reg.best_score_

np.float64(0.4977927380937258)

In [31]:
final_model = reg.best_estimator_

In [32]:
y_pred = final_model.predict(X_test)
r2_score(y_test, y_pred)

0.4862264153537742