In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [98]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [99]:
# predict the total_bill? i.e. total_bill is target variable
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [100]:
#EDA>> subjective
#encoding, missing value treatment, scaling>> automate
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [101]:
X = df.drop('total_bill', axis =1)
y = df['total_bill']

In [102]:
X.shape, y.shape

((244, 6), (244,))

In [103]:
X

      tip     sex smoker   day    time  size
0    1.01  Female     No   Sun  Dinner     2
1    1.66    Male     No   Sun  Dinner     3
2    3.50    Male     No   Sun  Dinner     3
3    3.31    Male     No   Sun  Dinner     2
4    3.61  Female     No   Sun  Dinner     4
..    ...     ...    ...   ...     ...   ...
239  5.92    Male     No   Sat  Dinner     3
240  2.00  Female    Yes   Sat  Dinner     2
241  2.00    Male    Yes   Sat  Dinner     2
242  1.75    Male     No   Sat  Dinner     2
243  3.00  Female     No  Thur  Dinner     2

[244 rows x 6 columns]

In [104]:
y

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.3)

In [106]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((170, 6), (74, 6), (170,), (74,))

In [107]:
X_train

      tip     sex smoker   day    time  size
203  2.50  Female    Yes  Thur   Lunch     2
56   3.00    Male    Yes   Sat  Dinner     4
123  2.00    Male     No  Thur   Lunch     2
61   2.00    Male    Yes   Sat  Dinner     2
92   1.00  Female    Yes   Fri  Dinner     2
..    ...     ...    ...   ...     ...   ...
130  1.50    Male     No  Thur   Lunch     2
86   2.00    Male     No  Thur   Lunch     2
42   3.06    Male     No   Sun  Dinner     2
151  2.00    Male     No   Sun  Dinner     2
46   5.00    Male     No   Sun  Dinner     2

[170 rows x 6 columns]

In [108]:
X_test

      tip     sex smoker   day    time  size
79   2.71    Male     No  Thur   Lunch     2
59   6.73    Male     No   Sat  Dinner     4
2    3.50    Male     No   Sun  Dinner     3
132  1.50  Female     No  Thur   Lunch     2
237  1.17    Male    Yes   Sat  Dinner     2
..    ...     ...    ...   ...     ...   ...
165  3.48    Male     No   Sun  Dinner     3
108  3.76    Male     No   Sat  Dinner     2
5    4.71    Male     No   Sun  Dinner     4
154  2.00    Male     No   Sun  Dinner     4
119  2.92  Female     No  Thur   Lunch     4

[74 rows x 6 columns]

In [109]:
y_train

203    16.40
56     38.01
123    15.95
61     13.81
92      5.75
       ...
130    19.08
86     13.03
42     13.94
151    13.13
46     22.23
Name: total_bill, Length: 170, dtype: float64

In [110]:
y_test

79     17.29
59     48.27
2      21.01
132    11.17
237    32.83
       ...
165    24.52
108    18.24
5      25.29
154    19.77
119    24.08
Name: total_bill, Length: 74, dtype: float64

In [111]:
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [112]:
#Handling the missing value
#data encoding
#feature scaling

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [114]:
cat_cols = ["sex", "smoker", "day", "time"]
num_cols = ["tip", "size"]

In [115]:
#feature engineering automation using pipeline and columntransformer

num_pipeline = Pipeline(steps= [('imputation', SimpleImputer(strategy= 'median')),
                                ('scaling', StandardScaler())])

cat_pipeline = Pipeline(steps= [('imputation', SimpleImputer(strategy= 'most_frequent')),
                                ('encoding', OneHotEncoder())])

preprocessor = ColumnTransformer([("num_pipeline", num_pipeline, num_cols),
                                  ("cat_pipeline", cat_pipeline, cat_cols)])

preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['tip', 'size']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder())]),
                                 ['sex', 'smoker', 'day', 'time'])])

In [116]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [117]:
X_train

array([[-0.28097378, -0.57830945,  1.        , ...,  1.        ,
         0.        ,  1.        ],
       [ 0.10933136,  1.53594016,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.67127893, -0.57830945,  0.        , ...,  1.        ,
         0.        ,  1.        ],
       ...,
       [ 0.15616797, -0.57830945,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.67127893, -0.57830945,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 1.67055192, -0.57830945,  0.        , ...,  0.        ,
         1.        ,  0.        ]])

In [118]:
X_test

array([[-0.11704562, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 3.02100771,  1.53594016,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.4996365 ,  0.47881535,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-1.06158407, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-1.31918546, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.72519464,  1.53594016,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.79544957,  1.53594016,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.67127893, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.10061458, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 2.9975894 ,  3.65018977,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.67127893, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.28097378,  0.47881535,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.8664315 , -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.28097378, -0.57830945,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ],
       [ 0.88994164, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.88994164, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.10933136, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.66356466,  0.47881535,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.28097378, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.10933136,  1.53594016,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.28097378, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.67055192, -0.57830945,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.67127893, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.24194327, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.4996365 ,  0.47881535,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.23413717, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.66347282, -0.57830945,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 1.45978715,  1.53594016,  0.        ,  1.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.5074426 , -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.88994164, -0.57830945,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-1.45188921, -1.63543426,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.10842068, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 2.45116221,  1.53594016,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.88994164, -0.57830945,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.88994164, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.28887172, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.28097378, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.78764347, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.08582121, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.02337239, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 3.68452645,  1.53594016,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.20291276, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.95239046, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.27325952, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.95239046, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 4.79299306,  1.53594016,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.48402429, -0.57830945,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ],
       [-0.09362732,  0.47881535,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.4996365 , -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 1.11631862, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.93677826, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.06158407, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.67055192,  2.59306497,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 2.13891809,  1.53594016,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.51515687, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.67127893,  0.47881535,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.88994164, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.67127893,  0.47881535,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.06158407, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.67055192,  1.53594016,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.28097378, -0.57830945,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.96010473, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-1.01474745, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-1.06158407, -0.57830945,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.17958628,  1.53594016,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.26536158, -0.57830945,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-0.3200043 ,  1.53594016,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.10933136,  0.47881535,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.17168834,  0.47881535,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.48402429,  0.47881535,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.70259517, -0.57830945,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 1.44417494,  1.53594016,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-0.67127893,  1.53594016,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.04688254,  1.53594016,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ]])

In [119]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [120]:
models = {
    "support_vector_regressor": SVR(),
    "DT Regressor": DecisionTreeRegressor(),
    "Multiple Linear Regression": LinearRegression(),
    "random_forest": RandomForestRegressor()
}

models

{'support_vector_regressor': SVR(),
 'DT Regressor': DecisionTreeRegressor(),
 'Multiple Linear Regression': LinearRegression(),
 'random_forest': RandomForestRegressor()}

In [121]:
from sklearn.metrics import r2_score

In [122]:
def model_train_evaluation(X_train, y_train, X_test, y_test, models):
  evaluation = {}
  for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    model_score = r2_score(y_test, y_pred)
    evaluation[list(models.keys())[i]] = model_score
  return evaluation

In [123]:
model_train_evaluation(X_train, y_train, X_test, y_test, models)

{'support_vector_regressor': 0.2461048584797696,
 'DT Regressor': 0.1700575285984156,
 'Multiple Linear Regression': 0.45852192018296234,
 'random_forest': 0.35650754380312344}

In [124]:
from sklearn.ensemble import RandomForestRegressor

In [125]:
rf_r = RandomForestRegressor(oob_score= True)
rf_r

RandomForestRegressor(oob_score=True)

In [126]:
from sklearn.model_selection import RandomizedSearchCV
params={'max_depth':[1,50, 100, 150,200],
        'n_estimators':[50, 100,200]}

In [127]:
reg = RandomizedSearchCV(rf_r, param_distributions= params, cv= 5, verbose= 3, scoring= 'r2')
reg

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(oob_score=True),
                   param_distributions={'max_depth': [1, 50, 100, 150, 200],
                                        'n_estimators': [50, 100, 200]},
                   scoring='r2', verbose=3)

In [ ]:
reg.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END ...max_depth=200, n_estimators=200;, score=0.460 total time=   0.5s
[CV 2/5] END ...max_depth=200, n_estimators=200;, score=0.317 total time=   0.5s
[CV 3/5] END ...max_depth=200, n_estimators=200;, score=0.505 total time=   0.9s
[CV 4/5] END ...max_depth=200, n_estimators=200;, score=0.567 total time=   0.5s
[CV 5/5] END ...max_depth=200, n_estimators=200;, score=0.576 total time=   0.5s
[CV 1/5] END .....max_depth=1, n_estimators=100;, score=0.319 total time=   0.2s
[CV 2/5] END .....max_depth=1, n_estimators=100;, score=0.277 total time=   0.3s
[CV 3/5] END .....max_depth=1, n_estimators=100;, score=0.426 total time=   0.2s
[CV 4/5] END .....max_depth=1, n_estimators=100;, score=0.413 total time=   0.2s
[CV 5/5] END .....max_depth=1, n_estimators=100;, score=0.562 total time=   0.2s
[CV 1/5] END ...max_depth=150, n_estimators=100;, score=0.471 total time=   0.2s
[CV 2/5] END ...max_depth=150, n_estimators=100;, score=0.286 total time=   0.2s
[CV 3/5] END ...max_depth=150, n_estimators=100;, score=0.491 total time=   0.2s
[CV 4/5] END ...max_depth=150, n_estimators=100;, score=0.580 total time=   0.3s
[CV 5/5] END ...max_depth=150, n_estimators=100;, score=0.574 total time=   0.2s
[CV 1/5] END ....max_depth=200, n_estimators=50;, score=0.477 total time=   0.1s
[CV 2/5] END ....max_depth=200, n_estimators=50;, score=0.316 total time=   0.1s
[CV 3/5] END ....max_depth=200, n_estimators=50;, score=0.537 total time=   0.2s
[CV 4/5] END ....max_depth=200, n_estimators=50;, score=0.572 total time=   0.1s
[CV 5/5] END ....max_depth=200, n_estimators=50;, score=0.601 total time=   0.2s
[CV 1/5] END ......max_depth=1, n_estimators=50;, score=0.324 total time=   0.1s
[CV 2/5] END ......max_depth=1, n_estimators=50;, score=0.263 total time=   0.1s
[CV 3/5] END ......max_depth=1, n_estimators=50;, score=0.410 total time=   0.1s
[CV 4/5] END ......max_depth=1, n_estimators=50;, score=0.432 total time=   0.1s
[CV 5/5] END ......max_depth=1, n_estimators=50;, score=0.505 total time=   0.1s
[CV 1/5] END ....max_depth=150, n_estimators=50;, score=0.474 total time=   0.1s
[CV 2/5] END ....max_depth=150, n_estimators=50;, score=0.245 total time=   0.1s
[CV 3/5] END ....max_depth=150, n_estimators=50;, score=0.485 total time=   0.1s

In [ ]:
reg.best_params_

In [ ]:
reg.best_score_

In [ ]:
final_model = reg.best_estimator_

In [ ]:
y_pred = final_model.predict(X_test)
r2_score(y_test, y_pred)