In [223]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.filterwarnings('ignore')

In [224]:
df = sns.load_dataset('mpg')

In [225]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [226]:
df.drop("name", axis=1, inplace = True)

In [227]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [228]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [229]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
dtype: object

In [230]:
df.shape

(398, 8)

In [231]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [232]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

In [233]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [234]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [235]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [236]:
#data encoding
df["origin"] = df["origin"].map({"usa":1, "japan":2, "europe":3})

In [237]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [238]:
X = df.drop('mpg', axis= 1)
y = df['mpg']

In [239]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [240]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [241]:
#train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=1)

In [242]:
# CV with hyperparameter tuning

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import Lasso, Ridge, ElasticNet

In [243]:
X_train.shape

(278, 7)

In [244]:
X_test.shape

(120, 7)

In [245]:
# gridsearchCV for lasso
# define by model

lasso = Lasso()

In [246]:
lasso

Lasso()

In [247]:
#grid search cv>> Dictionary with parameters names (str) as keys and lists of parameter settings to try as value

param_grid = {'alpha': [0.001, 0.01, 0.1, 1,2,5,10,100]}
param_grid

{'alpha': [0.001, 0.01, 0.1, 1, 2, 5, 10, 100]}

In [248]:
grid_search = GridSearchCV(estimator= lasso, param_grid= param_grid, cv= 5, scoring= 'r2', verbose= 2)

In [249]:
grid_search

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 2, 5, 10, 100]},
             scoring='r2', verbose=2)

In [250]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ............................................alpha=5; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 2, 5, 10, 100]},
             scoring='r2', verbose=2)

In [251]:
grid_search.best_params_

{'alpha': 0.1}

In [252]:
grid_search.best_params_['alpha']

0.1

In [253]:
grid_search.best_score_
#Mean cross-validated score of the best_estimator

np.float64(0.7964209726696481)

In [254]:
grid_search.best_estimator_
#Estimator that was chosen by the search, i.e. estimator which gave highest score (or smallest loss if specified) on the left out data

Lasso(alpha=0.1)

In [255]:
from sklearn.metrics import r2_score

In [256]:
y_pred = grid_search.best_estimator_.predict(X_test)
r2_grid = r2_score(y_test, y_pred)
print(f"The R square of GridSearchCV of Lasso regression: {r2_grid}")

The R square of GridSearchCV of Lasso regression: 0.8345318641232303

In [257]:
# randomized search cv for lasso

lasso = Lasso()
param_distributions = {'alpha': [0.01,0.1,1,2,10,100]}
random_search_lasso = RandomizedSearchCV(estimator= lasso, param_distributions= param_distributions, cv= 5, scoring='r2', verbose= 2, n_iter= 3)
random_search_lasso

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.01, 0.1, 1, 2, 10, 100]},
                   scoring='r2', verbose=2)

In [258]:
random_search_lasso.fit(X_train, y_train)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.01, 0.1, 1, 2, 10, 100]},
                   scoring='r2', verbose=2)

In [259]:
random_search_lasso.best_estimator_

Lasso(alpha=2)

In [260]:
random_search_lasso.best_score_

np.float64(0.7846578413793136)

In [261]:
y_random_pred = random_search_lasso.predict(X_test)
r2_random_lasso = r2_score(y_test, y_pred)
print(f"The R square of RandomizedSearchCV of Lasso regression: {r2_random_lasso}")

The R square of RandomizedSearchCV of Lasso regression: 0.8345318641232303

In [262]:
# grid search cv for ridge

ridge = Ridge()
param_grid = {'alpha': [0.01,0.1,1,2,10,100]}
grid_search_ridge = GridSearchCV(estimator= ridge, param_grid= param_grid, cv= 5, scoring='r2', verbose= 2)
grid_search_ridge.fit(X_train, y_train)
print("\n")
print(grid_search_ridge.best_estimator_)
print(grid_search_ridge.best_score_)
y_grid_pred = grid_search_ridge.best_estimator_.predict(X_test)
r2_random_ridge = r2_score(y_test, y_pred)
print(f"The R square of GridSearchCV of Ridge regression: {r2_random_ridge}")

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s


Ridge(alpha=10)
0.794358984633479
The R square of GridSearchCV of Ridge regression: 0.8345318641232303

In [263]:
# randomized search cv for ridge

ridge = Ridge()
param_distributions = {'alpha': [0.01,0.1,1,2,10,100]}
random_search_ridge = RandomizedSearchCV(estimator= ridge, param_distributions= param_distributions, cv= 5, scoring='r2', verbose= 2, n_iter= 4)
random_search_ridge.fit(X_train, y_train)
print("\n")
print(random_search_ridge.best_estimator_)
print(random_search_ridge.best_score_)
y_random_pred = random_search_ridge.predict(X_test)
r2_random_ridge = r2_score(y_test, y_pred)
print(f"The R square of RandomizedSearchCV of Ridge regression: {r2_random_ridge}")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s
[CV] END ............................................alpha=2; total time=   0.0s


Ridge(alpha=10)
0.794358984633479
The R square of RandomizedSearchCV of Ridge regression: 0.8345318641232303

In [264]:
# grid search cv for ElasticNet

model = ElasticNet()
param_grid = {'alpha': [0.01,0.1,1,2,10,100],
              'l1_ratio': [0.1,0.4,0.9]}
grid_search_elastic = GridSearchCV(estimator= model, param_grid= param_grid, cv= 5, scoring='r2', verbose= 2)
grid_search_elastic.fit(X_train, y_train)
print("\n")
print(grid_search_elastic.best_estimator_)
print(grid_search_elastic.best_score_)
y_grid_pred = grid_search_elastic.best_estimator_.predict(X_test)
r2_grid_elastic = r2_score(y_test, y_grid_pred)
print(f"The R square of GridSearchCV of ElasticNet regression: {r2_grid_elastic}")

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=2, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s


ElasticNet(alpha=0.1, l1_ratio=0.9)
0.7962409225488818
The R square of GridSearchCV of ElasticNet regression: 0.8345726087080976

In [265]:
# randomized search cv for ElasticNet

model = ElasticNet()
param_distributions = {'alpha': [0.01,0.1,1,2,5,10,100],
              'l1_ratio': [0.1,0.4,0.9]}
random_search_elastic = RandomizedSearchCV(estimator= model, param_distributions= param_distributions, n_iter= 4, cv= 5, scoring='r2', verbose= 2)
random_search_elastic.fit(X_train, y_train)
print("\n")
print(random_search_elastic.best_estimator_)
print(random_search_elastic.best_score_)
y_grid_pred = random_search_elastic.best_estimator_.predict(X_test)
r2_random_elastic = r2_score(y_test, y_grid_pred)
print(f"The R square of RandomizedSeaarchCV of Elastic regression: {r2_random_elastic}")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s


ElasticNet(alpha=1, l1_ratio=0.4)
0.7890047335456838
The R square of RandomizedSeaarchCV of Elastic regression: 0.8297233559893428